.\" Copyright 2010 Jason Record <jrecord@suse.com>
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; version 2 of the License.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\" 
.TH plugin_tag 3 "06 Oct 2010" "plugin_tag" "Supportconfig Plugin Library Manual"
.SH NAME
plugin_tag - Displays the message <string> with a section line that includes the <label>.
.SH SYNOPSIS
.B plugin_tag <label> <string>
.SH DESCRIPTION
Displays the message string with the <label> inside the section line and the <string> in the comment area. It is used frequently in place of 
.BR plugin_command (3)
when you want to display a different command than the one you actually execute.
.sp
Output:
.br
#==[ <label> ]======================================#
.br
# <string>
.sp
.SH EXAMPLES
The following plugin functions:
.sp
plugin_command "ls -al /mount/"
.br
plugin_tag "Command" "ls -l /mount/"
.br
ls -al /mount/
.sp
Would produce the following output:
.sp
#==[ Command ]======================================#
.br
# /bin/ls -al /mount/
.br
total 24
.br
drwxr-xr-x  2 jrecord users  4096 Oct  6 11:19 .
.br
drwxr-xr-x 62 jrecord users 12288 Oct  6 11:25 ..
.br
-rw-r--r--  1 jrecord users   300 Oct  6 11:19 xvmnt.conf
.br
-rw-r--r--  1 jrecord users   179 Oct  6 11:20 xvmnt.xml
.sp
#==[ Command ]===============================#
.br
# ls -l /mount/
.sp
total 24
.br
drwxr-xr-x  2 jrecord users  4096 Oct  6 11:19 .
.br
drwxr-xr-x 62 jrecord users 12288 Oct  6 11:25 ..
.br
-rw-r--r--  1 jrecord users   300 Oct  6 11:19 xvmnt.conf
.br
-rw-r--r--  1 jrecord users   179 Oct  6 11:20 xvmnt.xml
.SH REPORTING BUGS
Please submit bug fixes or comments via: 
.B http://en.opensuse.org/Supportutils#Reporting_Bugs
.SH AUTHOR
Jason Record <jrecord@suse.com>
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
.BR scplugin.rc (3)
.BR section_header (3)
.BR pconf_files (3)
.BR plog_files (3)
.BR plugin_message (3)
.BR plugin_command (3)
.BR validate_rpm (3)

