.TH SUPPORTCONFIG.RC 3 "27 Oct 2017" "supportutils" "Supportconfig Plugin Library Manual"
.SH NAME
supportconfig.rc - Supportconfig Plugin Resource File
.SH DESCRIPTION
Supportconfig plugin development library for bash script plugins. Plugins should be developed using the supportconfig.rc instead of scplugin.rc. The scplugin.rc is deprecated. Supportconfig uses supportconfig.rc which allows plugins to be written in the same way supportconfig functions are written. It also provides compatibility with the Supportconfig Analysis Tool.
.BR


.SH REPORTING BUGS
Please submit bug fixes or comments via: 
.B https://github.com/g23guy/supportutils/issues
.SH AUTHOR
Jason Record <jason.record@suse.com>
.SH COPYRIGHT
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 2 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, see <http://www.gnu.org/licenses/>.
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)

