.\" Copyright 2010 Jason Record <jrecord@suse.com>
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; version 2 of the License.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, see <http://www.gnu.org/licenses/>.
.\" 
.TH validate_rpm 3 "06 Oct 2010" "validate_rpm" "Supportconfig Plugin Library Manual"
.SH NAME
validate_rpm - Runs an rpm -V on the specified RPM package.
.SH SYNOPSIS
.B validate_rpm <command>
.SH DESCRIPTION
Used to confirm an installed RPM package is healthy. If no exceptions are found, it's marked Passed, otherwise it's marked WARNING.
.SH EXAMPLES
The following plugin commands:
.sp
for i in aaa_base glib
.br
do
.br
	validate_rpm $i
.br
done
.sp
Return the following results:
.sp
#==[ Validating RPM ]=================================#
.br
# rpm -V aaa_base
.br
..5....T  c /etc/inittab
.br
S.5....T  c /etc/mailcap
.br
S.5....T  c /etc/mime.types
.br
Status: WARNING
.sp
#==[ Validating RPM ]=================================#
.br
# rpm -V glib
.br
Status: Passed
.sp
.SH REPORTING BUGS
Please submit bug fixes or comments via: 
.B http://en.opensuse.org/Supportutils#Reporting_Bugs
.SH AUTHOR
Jason Record <jrecord@suse.com>
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
.BR scplugin.rc (3)
.BR section_header (3)
.BR pconf_files (3)
.BR plog_files (3)
.BR plugin_message (3)
.BR plugin_tag (3)
.BR plugin_command (3)

